### ISSUE TITLE
"Gift Shop" in the main README.md links to east/README.md

### ISSUE THREAD

**Issue by l74d** [elaraai/edk-examples#1]
The correct link seems to be gift_shop/ instead.

Moreover, the directory name "east" appears to mean "Expression AST" given the link "Expression". Is it so?

**Comment by mthomas88** [comment]
Hi @l74d,

Thank you for letting us know! 

We've updated the `README.md` link correctly now, thank you for pointing that out!

Regards,
The elara.ai team
